---

 - name: Precompile static assets
   command: bundle exec grunt
   become_user: "{{ install_user }}"
   args:
     chdir: "{{ cartodb_dir }}"
   when: cartodb_compile_assets

 - name: Ensure cartodb log dir exists
   file: path="{{ cartodb_dir }}/log" state=directory
   become_user: "{{ install_user }}"

 - name: Touch app_config.yml to ensure it exists
   file: path="{{ cartodb_dir }}/config/app_config.yml" state=touch

 - name: Copy app_config.yml template
   template: src=app_config.yml.j2 dest="{{ cartodb_dir }}/config/app_config.yml"

 - name: Touch database.yml to ensure it exists
   file: path="{{ cartodb_dir }}/config/database.yml" state=touch

 - name: Copy database.yml template
   template: src=database.yml.j2 dest="{{ cartodb_dir }}/config/database.yml"

 #- name: Create CartoDB database
 #  command: bundle exec rake db:create
 #  become_user: "{{ install_user }}"
 #  args:
 #    chdir: "{{ cartodb_dir }}"

 - name: Migrate CartoDB database
   command: bundle exec rake db:migrate
   become_user: "{{ install_user }}"
   args:
     chdir: "{{ cartodb_dir }}"

 - name: Create a cartodb user
   command: bundle exec rake cartodb:db:create_user SUBDOMAIN="{{ cartodb_user_subdomain }}" PASSWORD="{{ cartodb_user_password }}" EMAIL="{{ cartodb_user_email }}"
   become_user: "{{ install_user }}"
   args:
     chdir: "{{ cartodb_dir }}"

 - name: Create a common data user
   command: bundle exec rake cartodb:db:create_user QUOTA_IN_BYTES="{{ cartodb_common_data_user_data_quota }}" SUBDOMAIN="{{ cartodb_common_data_username }}" PASSWORD="{{ cartodb_common_data_user_password }}" EMAIL="{{ cartodb_common_data_user_email }}"
   become_user: "{{ install_user }}"
   args:
     chdir: "{{ cartodb_dir }}"
   when: cartodb_common_data_local

 - name: Move common data user to its own schema
   command: bundle exec rake cartodb:db:move_user_to_schema['{{ cartodb_common_data_username }}']
   become_user: "{{ install_user }}"
   args:
     chdir: "{{ cartodb_dir }}"
   when: cartodb_common_data_local

 - name: Remove table limit for common data user
   command: bundle exec rake cartodb:db:remove_table_quota USER_NAME="{{ cartodb_common_data_username }}"
   become_user: "{{ install_user }}"
   args:
     chdir: "{{ cartodb_dir }}"
   when: cartodb_common_data_import

 - name: Add cartodb user subdomain to hosts file
   lineinfile: dest=/etc/hosts line="127.0.0.1 {{ cartodb_user_subdomain }}.{{ cartodb_hostname }}"

 - name: Add common data user subdomain to hosts file
   lineinfile: dest=/etc/hosts line="127.0.0.1 {{ cartodb_common_data_username }}.{{ cartodb_hostname }}"
   when: cartodb_common_data_local

 - name: Add cartodb hostname to hosts file
   lineinfile: dest=/etc/hosts line="127.0.0.1 {{ cartodb_hostname }}"

 - name: Copy rails server job template
   template: src=cartodb_server.conf.j2 dest=/etc/init/cartodb_server.conf

 - name: Import common data to local user
   command: bundle exec rake cartodb:common_data:import_common_data
   become_user: "{{ install_user }}"
   args:
     chdir: "{{ cartodb_dir }}"
   register: import_result
   when: cartodb_common_data_import

 - debug: var=import_result.stdout_lines
   when: cartodb_common_data_import

 - name: Clear common data for development user
   command: bundle exec rake cartodb:remotes:clear['{{ cartodb_user_subdomain }}']
   become_user: "{{ install_user }}"
   args:
     chdir: "{{ cartodb_dir }}"
   when: cartodb_common_data_import

 - name: Reload common data for development user
   command: bundle exec rake cartodb:remotes:reload['{{ cartodb_user_subdomain }}']
   become_user: "{{ install_user }}"
   args:
     chdir: "{{ cartodb_dir }}"
   when: cartodb_common_data_import

 - include: setup_fdw.yml

 - include: add_org_account.yml

 - name: Start the CartoDB rails server
   service: name=cartodb_server state=restarted
