---

 - name: Add cartodb nodejs ppa
   apt_repository: repo=ppa:cartodb/nodejs-010 state=present update_cache=yes

 - name: Install nodejs 0.10.x
   apt: name=nodejs state=present

 - name: Update npm -- Carto requires 2.14.x to build cartodb.js
   npm: name=npm global=yes version={{ cartodb_npm_version }}
