---

  - name: Copy nginx sites-available
    template: src='nginx-site.{{ item }}.conf.j2' dest='/etc/nginx/sites-available/{{ item }}.conf'
    with_items: "{{ nginx_sites_available }}"

  - name: Symlink requested sites-available to sites-enabled
    file: path='/etc/nginx/sites-enabled/{{ item }}.conf' src='/etc/nginx/sites-available/{{ item }}.conf' state=link
    with_items: "{{ nginx_sites_enabled }}"
    when: nginx_sites_enabled is defined

  - name: Restart nginx
    service: name=nginx state=restarted
